filter:
    excluded_paths:
        - 'vendor/*'
        - 'js/vendor/*'
        - 'js/build/*'
        - 'l10n/*'
        - 'templates/*'
        - 'img/*'
        - 'css/*'
        - 'bin/*'
        - 'tmp/*'
        - 'appinfo/routes.php'
        - 'tests/*'

imports:
    #- javascript  disabled because of es6 producing tons of errors
    - php
    - javascript

#tools:
#    external_code_coverage:
#        timeout: 600

checks:
    php:
        # not helpful because there is no setting to tweek the threshold
        duplication: false
        # this is not working properly with core exceptions
        catch_class_exists: false
        avoid_tab_indentation: true
        line_length:
            max_length: '80'
