export const FEED_MUTATION_TYPES = {
	ADD_FEED: 'ADD_FEED',
	SET_FEEDS: 'SET_FEEDS',
}

export const FOLDER_MUTATION_TYPES = {
	SET_FOLDERS: 'SET_FOLDERS',
	DELETE_FOLDER: 'DELETE_FOLDER',
}

export const FEED_ITEM_MUTATION_TYPES = {
	SET_ITEMS: 'SET_ITEMS',
	UPDATE_ITEM: 'UPDATE_ITEM',
	SET_SELECTED_ITEM: 'SET_SELECTED_ITEM',

	SET_STARRED_COUNT: 'SET_STARRED_COUNT',
	SET_UNREAD_COUNT: 'SET_UNREAD_COUNT',

	SET_FETCHING: 'SET_FETCHING',
	SET_ALL_LOADED: 'SET_ALL_LOADED',
	SET_LAST_ITEM_LOADED: 'SET_LAST_ITEM_LOADED',
}
