import Vue from 'vue'
import VueRouter from 'vue-router'
import Vuex, { Store } from 'vuex'
import axios from '@nextcloud/axios'

import App from './App.vue'
import router from './routes'
import mainStore, { MUTATIONS } from './store'

import { Tooltip } from '@nextcloud/vue'

Vue.prototype.t = t
Vue.prototype.n = n
Vue.prototype.OC = OC
Vue.prototype.OCA = OCA

Vue.use(Vuex)
Vue.use(VueRouter)

Vue.directive('tooltip', Tooltip)

const store = new Store(mainStore)

axios.interceptors.response(undefined /* onSuccessCallback is intentionally undefined */,
	// Any status codes that falls outside the range of 2xx cause this function to trigger
	function(error) {

		store.commit(MUTATIONS.SET_ERROR, error)
		return Promise.reject(error)
	},
)

Vue.config.errorHandler = function(err) {
	store.commit(MUTATIONS.SET_ERROR, err)
}

export default new Vue({
	router,
	store,
	el: '#q-app',
	render: (h) => h(App),
})

/**
 * Closes warning messages generated by PHP code
 */
function closeCronWarning() {
	document.getElementById('cron-warning').style.display = 'none'
}
document.getElementById('close-cron-warning').onclick = closeCronWarning
