/**
 * Initially copied from typescript+vue2 project generated by @vue/cli-plugin v5.0.0
 */
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
};

declare module '@nextcloud/vue/dist/Components/Button' {

};