/**
 * Initially copied from typescript+vue2 project generated by @vue/cli-plugin v5.0.0
 */
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
};

// Necessary for All Nextcloud Vue components
declare module '@nextcloud/vue/dist/Components/*' {

};