/**
 * Initially copied from typescript+vue2 project generated by @vue/cli-plugin v5.0.0
 */
import Vue, { VNode } from "vue";

declare global {
  namespace JSX {
    interface Element extends VNode { }
    interface ElementClass extends Vue { }
    interface IntrinsicElements {
      [elem: string]: any;
    }
  }
  t;
  n;
  OC;
  OCA;
};