name: Lint stylelint

on:
  pull_request:
  push:
    branches:
      - master

permissions: {}

jobs:
  stylelint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    name: stylelint
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@06d6baf7d8f41934ab630e97d9e6c0bc9c9ac5e4 # v3
        id: versions
        with:
          fallbackNode: '^20'
          fallbackNpm: '^10'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run stylelint
